# ====================server====================
server:
  port: 9876
spring:
  thymeleaf:
    # 开发环境禁用页面缓存
    cache: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates
    suffix: .html
  redis:
      # 数据库索引
      database: 0
      host: 127.0.0.1
      port: 6379
      jedis:
          pool:
              # 最大连接数
              max-active: 8
              # 最大空闲
              max-idle: 8
              # 最小空闲
              min-idle: 4
          # 连接超时时间
          timeout: 10000

# ====================doe====================
doe:
  dependency:
    # 用于下载依赖的pom文件
    pom: /app/doe/pom.xml
    # 用于存放下载的jar的目录
    lib: /app/doe/lib/
    # 用于执行mvn命令超时时间（秒）
    timeout: 20
  watchdog:
    url: http://localhost:8000